### ISSUE TITLE
Can't rotate the kelp reservoir.

### ISSUE THREAD

**Issue by demethan** [davqvist/aoe#1]
![image](https://github.com/user-attachments/assets/7f1d7337-02be-4daa-8523-a8c5d1e1580d)

Not sure if you can rotate those or if it's because you will have your own art later.   Its not obvious where to plug in the water pipes.

**Comment by demethan** [comment]
Ok. its just the image that doesn`t rotate.. the block logic does.

**Comment by davqvist** [comment]
Yeah that is how most blocks in (especially modded) Factorio work. Not everything has a rotatable different art.
