### ISSUE TITLE
Latex first setup.

### ISSUE THREAD

**Issue by demethan** [davqvist/aoe#3]
Latex setup is a bit long compared to the rest of the beginning setup.w  Getting 1 seed every 10-30 min (didn`t time, feels that way). 

Suggestion:  cutting a mature rubber tree yields 2 seeds.

**Comment by davqvist** [comment]
I am confused. If you don't mind, let me know how you did set this up. 
You are supposed to craft like 20 seeds from the Gene Lab and then plant them around a Forestry and then tap them indefinitely. Why does it take so long to get the seeds for you? You are not supposed to cut the trees down. 
I'd rather make the rubber tree seeds cheaper if you feel they are too expensive.

**Comment by davqvist** [comment]
Maybe you are coinfused about the planting process, you can manually plant them, you don't need the tower to do so.

**Comment by demethan** [comment]
I get one seed per hour ish..

**Comment by demethan** [comment]
The rods for the latex is burning pretty fast..  is there progression later to reduce the resources sink

**Comment by demethan** [comment]
> Maybe you are coinfused about the planting process, you can manually plant them, you don't need the tower to do so. Here the entry from the T&T page. ![image](https://private-user-images.githubusercontent.com/586922/397408306-d2f47cc1-03a8-4635-800a-51f2097db4f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjE4MzIsIm5iZiI6MTczNDYyMTUzMiwicGF0aCI6Ii81ODY5MjIvMzk3NDA4MzA2LWQyZjQ3Y2MxLTAzYTgtNDYzNS04MDBhLTUxZjIwOTdkYjRmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQxNTE4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTQ0N2FhMWM1M2MyZTdmN2Y1NjE0MDFhZDQzODE4ODMyYWZmMGM5MzhjODllNmM1NjFjNWY3NjNjYmFiZDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W24kLbhZp4LmshhwvuWbXEZIrWTPXc-8Z2q_rPi-648)

Not confused..  :)

**Comment by davqvist** [comment]
Are you forgetting the better recipe for bacteria? You are only supposed to use the éxpensive bacteria recipe like 10 times, then it replicates itself. Is that the issue maybe?
The latex recipe is more successful the more covered the green area is with fully grown rubber trees. So you should get 10 latex at best from every rod. But yes, you get a much better recipe later.

**Comment by davqvist** [comment]
No problem, oversights are helpful for me too, that makes me wanna mention those things in the T&T page
