### ISSUE TITLE
crafting numbers

### ISSUE THREAD

**Issue by demethan** [davqvist/aoe#4]
I notice that hovering on belts will show resources available for 3 as an example, and when I craft those 3, the crafting sequence will show 3 crafting, but I will get twice as much in the inventory.  I figure you probably cranked the output per resource, but it's not showing the same everywhere.

Same with the inserters.
 
![image](https://github.com/user-attachments/assets/1070623f-6f36-41a7-bf4e-8a29b949e649)
![image](https://github.com/user-attachments/assets/44b9fec4-9a22-4108-985f-1e9857aa9f9e)
![image](https://github.com/user-attachments/assets/f5a9cfcc-056a-4709-8eb7-e59dd93ed821)
![image](https://github.com/user-attachments/assets/d5413056-6230-4b82-ba5c-68c291d49f52)

**Comment by davqvist** [comment]
It shows you get 2 inserters. Normal vanilla behaviour. Nothing special about it in my mod. 
![image](https://github.com/user-attachments/assets/4fe2bfa3-68a9-4242-8b94-ae837d4972ba)
