### ISSUE TITLE
automation

### ISSUE THREAD

**Issue by demethan** [davqvist/aoe#5]
Do you have a good layout for the burner crushers and the mesh?  The mesh and coal requirement makes it difficult to automate.  Especially due to the reusability of the mesh. 

![image](https://github.com/user-attachments/assets/3ec1fa4b-a21e-4aa4-84f5-534af61162d1)

**Comment by davqvist** [comment]
Yeah it is supposed to be a bit painful til you get the electric version which isn't that far away. They don't use much power so I personally have put the mesh with the stone on the belt and filled them up full with charcoal manually every once in a while.

**Comment by davqvist** [comment]
I noticed this wasn't very clear. Here is a picture to show 
![image](https://github.com/user-attachments/assets/4ad761ba-9256-4da2-9b20-91d76e1b48c0)

**Comment by demethan** [comment]
ah.. I had forgotten about that technic. Thx.
