### ISSUE TITLE
[bug?]  Getting Zinc before unlocked with recyclers.

### ISSUE THREAD

**Issue by demethan** [davqvist/aoe#7]
I was getting Zn ore from the recyclers from aluminum but it is not available in the "JEI" to set filters and stuff. 

![image](https://github.com/user-attachments/assets/588d4185-4a20-49b5-b96e-b269ffb28bcd)
Im in age 3 

![image](https://github.com/user-attachments/assets/16df0497-9bf8-44e1-8654-fa1af90ac3c1)
![image](https://github.com/user-attachments/assets/fae04f02-75dc-409b-bf36-2146de45b6bd)

**Comment by davqvist** [comment]
Fixed for next version

**Comment by davqvist** [comment]
And that version is released now
